---
development:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors/doors_development.sqlite

test:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors/doors_test.sqlite

production:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors/doors_production.sqlite
