---
development:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors_doors_development.sqlite

test:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors_doors_test.sqlite

production:
  dialect: "sqlite3"
  database: /workspaces/buffalo/doors_doors_production.sqlite
