---
development:
  dialect: "sqlite3"
  database: /home/nka/Projects/work/dev/doory/doors_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/nka/Projects/work/dev/doory/doors_test.sqlite

production:
  dialect: "sqlite3"
  database: /var/doors_prod.sqlite
